### ISSUE TITLE
Allow management of the HostCertificate and TrustedUserCAKeys

### ISSUE THREAD

**Issue by dhollinger** [ghoneycutt/puppet-module-ssh#221]
We need the ability to manage the `HostCertificate` option for the SSH Daemon.

Suggestion:

`sshd_host_certificate` parameter to set the `HostCertificate` option. The value would be a `String`, or in Puppet 4 Data Types, an `Stdlib::Absolutepath` type.

`sshd_user_trusted_ca` parameter to set the `TrustedUserCAKeys` option. The value would be a `String` or an `Array` of `String`s. In Puppet 4 Data Types, that would be a `Stdlib::Absolutepath` or an `Array` of `Stdlib::Absolutepath` data types.

**Comment by ghoneycutt** [comment]
Sounds great! Could you please send me a pull request? New parameters need to be documented in the README, be validated in the manifest (`validate_()` functions) and have spec tests.

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
