### ISSUE TITLE
Warning of exported resources

### ISSUE THREAD

**Issue by fnoop** [ghoneycutt/puppet-module-ssh#229]
If using this module on a system without exported resources (which is reasonably common, and the only option for masterless setups), then you get two warnings:
```
Warning: You cannot collect exported resources without storeconfigs being set; the export is ignored at /srv/maverick/software/maverick/manifests/puppet-modules/ssh/manifests/init.pp:935:3
Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored at /srv/maverick/software/maverick/manifests/puppet-modules/ssh/manifests/init.pp:953:5
```
The second can be suppressed by setting:
`ssh_key_import              => false`

The export however is unconditional.  It should be wrapped by an option so it can be turned off, and the warning suppressed.

**Comment by ghoneycutt** [comment]
It is just a warning, not an error, so it is OK, though I understand that you would rather not see it. Could you create a parameter, ssh_key_export, and send a PR?

**Comment by achevalet** [comment]
Hi there, could we have this merged?

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
