### ISSUE TITLE
module fails hard if openssh server not installed

### ISSUE THREAD

**Issue by fnoop** [ghoneycutt/puppet-module-ssh#238]
If openssh server is not installed, this module fails a puppet run hard:
```
Error: Evaluation Error: Unknown variable: '::sshrsakey'. at /srv/maverick/software/maverick/manifests/puppet-modules/ssh/manifests/init.pp:742:14 on node maverick-ubuntuvm.local
```
It shouldn't fail the entire puppet run if the server is not installed.

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
