### ISSUE TITLE
ServerKeyBits Deprecated in RHEL 7.4

### ISSUE THREAD

**Issue by spacezer0** [ghoneycutt/puppet-module-ssh#244]
As of RHEL 7.4 ServerKeyBits is now a deprecated option.

Warning Message in /var/log/messages:
Deprecated option ServerKeyBits

**Comment by smokris** [comment]
The `ServerKeyBits` option [only applies to SSH protocol version 1](https://man.openbsd.org/OpenBSD-6.0/sshd_config).  Support for that was [removed in OpenSSH version 7.6](https://www.openssh.com/txt/release-7.6), so this issue occurs not just on RHEL but on any system running OpenSSH 7.6 or later.  PR #259 removes that option from the Puppet-generated `sshd_config`.

**Comment by westbywest** [comment]
In addition, having this parameter take the string 'USE_DEFAULTS' as its default value prevents one from setting the param to undef to deactivate the line in sshd_config.  I.e. the module can't be made to not insert a ServerKeyBits value into sshd_config.

**Comment by irekpo** [comment]
Hi Guys,
I don't think this problem is fixed. I am using the latest Centos (7.5.1804). I was using previous version of you module when I have noticed the problem. However after the upgrade ghoneycutt-ssh (v3.54.0 -> v3.57.0) the problem stays. I need to modify your code to fix that. Did I missed some steps or the code needs some correction?

**Comment by mears148** [comment]
This is the same for RhostsRSAAuthentication...also a deprecated option as of 7.4.

**Comment by mears148** [comment]
I'd make the change but I have little free time at the moment.
