### ISSUE TITLE
Making configurable AllowAgentForwarding possible

### ISSUE THREAD

**Issue by edwardvanhazendonk** [ghoneycutt/puppet-module-ssh#255]
Hi,

Is it possible to make AllowAgentForwarding in sshd_config a configurable parameter?
We need this for our puppet environment and would like to close the forwarding possibility.

Snippet from manpage:
     AllowAgentForwarding
             Specifies whether ssh-agent(1) forwarding is permitted.  The default is yes.  Note that disabling agent
             forwarding does not improve security unless users are also denied shell access, as they can always
             install their own forwarders.

Thanks in advance, regards,

Edward van Hazendonk

**Comment by ghoneycutt** [comment]
Hi @edwardvanhazendonk 

I would be happy to merge this if you could please send a pull request.

**Comment by edwardvanhazendonk** [comment]
Hi @ghoneycutt 

This will be the first pull request for github, I'll need some time.

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
