### ISSUE TITLE
Confusing entries in sshd template 

### ISSUE THREAD

**Issue by ggeldenhuis** [ghoneycutt/puppet-module-ssh#268]
The sshd template contains a line: 
```
# $OpenBSD: sshd_config,v 1.73 2005/12/06 22:38:28 reyk Exp $
```
What is this line suppose to signify. When you use the module and generate a config file, the first assumption is that module mistook Red Hat for OpenBSD until you open the template and realise it is just a static entry.

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
