### ISSUE TITLE
Manage by puppet should be more specific

### ISSUE THREAD

**Issue by ggeldenhuis** [ghoneycutt/puppet-module-ssh#269]
A colleague new to puppet recently mentioned that it would be useful know which puppet module manages  a file when you read in a config file that it is managed by puppet. I know it should be obvious but I think there might be some mileage in changing the default line to managed by ssh puppet module as opposed to just a generic managed by puppet statement.

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
