### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by fnoop** [ghoneycutt/puppet-module-ssh#273]
There are numerous problems with this module, previous PRs have been completely ignored and there is a growing list.  Before I rebase and resubmit, is this project still alive?
Perhaps a good time to migrate it to voxpupuli?

**Comment by ggeldenhuis** [comment]
Yeah would love to see some activity again. saz/ssh has recently seen activity again so might be a viable alternative.

**Comment by Ozzard** [comment]
I'm inclined to fork it and maintain it until Garrett has bandwidth again.  If I do, would you be interested?

**Comment by fnoop** [comment]
@Ozzard I was thinking of doing the same, but happy to work on your fork.  Ideally this would go to voxpopuli eventually.

**Comment by Ozzard** [comment]
Agree.  OK... https://github.com/Ozzard/puppet-module-ssh

**Comment by fnoop** [comment]
Great :)

**Comment by fnoop** [comment]
Do we continue using issues here to communicate?

**Comment by ggeldenhuis** [comment]
Its a bit more effort but why not try and get the module under voxpupili ownership rather than a fork?

**Comment by Ozzard** [comment]
I'd quite like to leave them with something that doesn't need too much more tidyup - but, yes, I also don't want to maintain it for the next fifteen years and that's the obvious home.

My email address (well-known, so I have no issues putting it on here) for direct comms: peter@ozzard.org.

**Comment by ghoneycutt** [comment]
Hi,

I'm happy to merge any PR's that contain spec tests and documentation and pass CI. If you have a PR that meets that criteria and is languishing, please ping me on it and I'll get merging.

I'm reworking this module under a new pattern sgnl05/sssd[1] where you specify all the data you want for the config files and then will have defaults for different platforms. That approach is needed instead of the current one because of how flexible the configuration is. For instance, the whole config can be repeated numerable times for different host matchers.

[1] - https://github.com/sgnl05/sgnl05-sssd/blob/master/templates/sssd.conf.erb

**Comment by TheMeier** [comment]
@ghoneycutt https://github.com/ghoneycutt/puppet-module-ssh/pull/271
the only reason CI fails ist the tests with _ancient_ puppet versions.

**Comment by ghoneycutt** [comment]
Check out https://github.com/ghoneycutt/puppet-module-ssh/pull/307 for the new version that is in progress.
