### ISSUE TITLE
CentOS 7: this module doesn't recognize sshd service is running

### ISSUE THREAD

**Issue by shawnxue** [ghoneycutt/puppet-module-ssh#286]
We have a server that is hosting Gitlab EE instance (omni package), puppet run is trying to start sshd service because it thinks this service is stopped. But actually, it is running.

OS: CentOS Linux release 7.4.1708 (Core)
Puppet version: 4.10.12
**Debug output:**
Debug: Using cached connection for https://puppetserver.service.discover:8140
Debug: Caching connection for https://puppetserver.service.discover:8140
Debug: Executing: '/bin/systemctl is-active sshd'
Debug: Executing: '/bin/systemctl is-enabled sshd'
Debug: Executing: '/bin/systemctl unmask sshd'
Debug: Executing: '/bin/systemctl start sshd'
Debug: Executing: '/bin/systemctl is-enabled sshd'
Notice: /Stage[main]/Ssh/Service[sshd_service]/ensure: ensure changed 'stopped' to 'running'
Debug: /Stage[main]/Ssh/Service[sshd_service]: The container Class[Ssh] will propagate my refresh event
Info: /Stage[main]/Ssh/Service[sshd_service]: Unscheduling refresh on Service[sshd_service]
Debug: Class[Ssh]: The container Stage[main] will propagate my refresh event

**Service is actually running (it has been running for many days)**
[root@gitlab ~]# systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-08-29 18:30:20 UTC; 6 days ago
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 405 (sshd)
   CGroup: /system.slice/sshd.service
           └─405 /usr/sbin/sshd -D

**Comment by ghoneycutt** [comment]
Thank you for clearly reporting this! This seems like a bug with the service provider in Puppet and not with the module. Suggest opening a ticket with Puppet and adding me as a watcher.

When `systemctl status sshd` works and shows that sshd is running, what happens when you try with puppet using `puppet resource service sshd`? Does it say that the service is stopped?

**Comment by Ozzard** [comment]
$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
$ puppet --version
4.10.12
$ sudo systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-12-10 09:51:37 UTC; 5min ago
[...]
$ sudo puppet resource service sshd
service { 'sshd':
  ensure => 'running',
  enable => 'true',
}

**Comment by Phil-Friderici** [comment]
Closing as CentOS 7 should work correct in v4.
Please re-open if this doesn't fit your use case.
