### ISSUE TITLE
Inconsistent hash_known_hosts behaviour, inaccurate documentation

### ISSUE THREAD

**Issue by jjjwww** [ghoneycutt/puppet-module-ssh#313]
Re: ssh_config_hash_known_hosts, the readme states:

"The default is 'no' on Linux."

The actual defaults appear to be:

RedHat: no
Suse: no
Ubuntu 16.04 and 18.04: yes
Debian 7, Ubuntu 7.04 and 7.10: no
Debian 8, 9, Ubuntu 8.04, 8.10, 9.04 and 9.10: yes

**Comment by TheMeier** [comment]
All the defaults in the README.md are only what is set in parameter initialization, the actual defaults have to be looked up in https://github.com/ghoneycutt/puppet-module-ssh/blob/master/manifests/init.pp#L127-L391
Its probably best to not list the defaults in the readme at all and instead provide hints how to find them

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
