### ISSUE TITLE
Not working on Cumulus 

### ISSUE THREAD

**Issue by achevalet** [ghoneycutt/puppet-module-ssh#345]
module version: 3.61.0

`Evaluation Error: Error while evaluating a Function Call, Operating System : 4.2.0 not supported at ...`

```
# facter os.distro
{
  codename => "buster",
  description => "Cumulus Linux",
  id => "Cumulus-Linux",
  release => {
    full => "4.2.0",
    major => "4",
    minor => "2"
  }
}
```

Thank you!

**Comment by ghoneycutt** [comment]
This module no longer fails by default on unknown platforms.

Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
