### ISSUE TITLE
Documentation?  How to?

### ISSUE THREAD

**Issue by wes-reneau** [ghoneycutt/puppet-module-ssh#347]
Very new to puppet but stumbled across this module that shows much promise based on what I've seen/read.

However, how does one use it?

I see that sshd_config_kexalgorithms is listed as an option but no where do I see how to define it?  Have I overlooked the documentation?

I'm not using Hiera btw.

Other modules gave examples of how to use this/that just don't see the syntax I guess.

Help appreciated.

**Comment by ghoneycutt** [comment]
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).
