### ISSUE TITLE
ABANDONED: Please Review open PR's and tickets

### ISSUE THREAD

**Issue by oniGino** [ghoneycutt/puppet-module-ssh#358]
@ghoneycutt you seem to still be very active on github, but this project has been ignored now for over a year,
Its a good module but these issues are starting to cause serious blocks in the latest puppet releases.

Please  either
- officially abandon in forge
- Ask to be moved into community puppetlabs
- Assign other community members permissions on the project to allow for maintenance to be maintained

Thanks!

Similar to #338

**Comment by ghoneycutt** [comment]
@oniGino This module was built organically and just enough to solve the immediate needs. Because of this the design is not great and making changes is difficult. To aid in this, I started a new version that is feature complete to the man pages. That work is in https://github.com/ghoneycutt/puppet-module-ssh/pull/307

If you would like to send pull requests to that branch, I would happily review and merge them.

**Comment by oniGino** [comment]
Thanks for your quick response, I'll retarget my infrastructure for your development branch. 

I'll leave this open just in-case others wish to know more or contribute to this project.
